update workflow to check http status

diff --git a/.github/workflows/metadata-workflow.yml b/.github/workflows/metadata-workflow.yml
--- a/.github/workflows/metadata-workflow.yml
+++ b/.github/workflows/metadata-workflow.yml
@@ -16,9 +16,16 @@ jobs:
         ref: ${{ github.head_ref }}
 
     - name: Fetch files
+      id: fetch
       run: |
-        curl -sSL -o src/components/HealthCardDisplay/iisstandards_cvx.xml https://www2a.cdc.gov/vaccines/iis/iisstandards/XML2.asp?rpt=cvx
-        curl -sSL -o src/components/HealthCardDisplay/iisstandards_tradename.xml https://www2a.cdc.gov/vaccines/iis/iisstandards/XML.asp?rpt=tradename
+        echo "::set-output name=cvx_status::$(curl -sSL -s -w '%{http_code}' -o src/components/HealthCardDisplay/iisstandards_cvx.xml https://www2a.cdc.gov/vaccines/iis/iisstandards/XML2.asp?rpt=cvx)"
+        echo "::set-output name=tradename_status::$(curl -sSL -s -w '%{http_code}' -o src/components/HealthCardDisplay/iisstandards_tradename.xml https://www2a.cdc.gov/vaccines/iis/iisstandards/XML.asp?rpt=tradename)"
+
+    - name: Check http files
+      if: steps.fetch.outputs.cvx_status > 200 || steps.fetch.outputs.tradename_status > 200
+      run: |
+        echo "::error title=Fetch::Failed to fetch CDC files"
+        exit 1
 
     - name: Check dirty files
       run: git diff --quiet --exit-code
